import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import KonvaWrapper from "../components/konva-wrapper/konva-wrapper.component"
import { KONVA_WIDTH_SCALE, KONVA_HEIGHT_SCALE } from '@/global'
import { useDispatch, useSelector } from 'react-redux';
import { setIsRecording, setTouches } from '../redux/screen-event/screen-event.actions';
import { selectIsRecording } from '@/redux/screen-event/screen-event.selectors'
import ScreenEventWrapper from '@/components/screen-event-wrapper/screen-event-wrapper.component'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ScreenEventWrapper>
          <div style= {{"width":+{KONVA_WIDTH_SCALE}+"px", "height":+{KONVA_HEIGHT_SCALE}+"px", "backgroundColor": "grey"}}>
            <KonvaWrapper/>
          </div>
        </ScreenEventWrapper>
      </main>
    </>
  )
}


class Controller {
  constructor(){

  }
}