const KonvaActionTypes = {
  ADD_MATERIAL_DATA: "ADD_MATERIAL_DATA",
  UPDATE_MATERIAL_DATA: "UPDATE_MATERIAL_DATA",
  SET_DRAGGABLE_ICON: "SET_DRAGGABLE_ICON",
  SET_DRAGGING_BLOCK_DIM_MENU: "SET_DRAGGING_BLOCK_DIM_MENU",
  SET_PAD_POSITION: "SET_PAD_POSITION",
  SET_ICON_POSITION: "SET_ICON_POSITION",
  UPDATE_DRAGGABLE_ICON_POSITION:"UPDATE_DRAGGABLE_ICON_POSITION",
  SET_PLAN_STATE_SPACE: "SET_PLAN_STATE_SPACE",
  SET_TAPPING_ON_ICON_BUTTON: "SET_TAPPING_ON_ICON_BUTTON",
  SET_ADD_BLOCK_MENU_STATE_SPACE: "SET_ADD_BLOCK_MENU_STATE_SPACE"
};
  
export default KonvaActionTypes;
  